export const ADMIN_ROUTE ='/admin'
export const RECIPE_ROUTE ='/recipe'
export const LOGIN_ROUTE ='/login'
export const REGISTRATION_ROUTE ='/registration'
export const MAIN_ROUTE ='/'
export const CREATE_ROUTE ='/create'